class TransactionModel {
  final String payeeName;
  final String payeeID;
  final String payeeMobileNumber;
  final String payerName;
  final String payerID;
  final String payerMobileNumber;
  final String transactionID;
  final String transactionMode;
  final String transactionStatus;
  final String date;
  final String time;
  final String currency;
  final String amount;
  final String payeeAvatarUrl;
  final String payerAvatarUrl;

  TransactionModel(
      {this.payeeName,
      this.payeeID,
      this.payeeMobileNumber,
      this.payerName,
      this.payerID,
      this.payerMobileNumber,
      this.transactionID,
      this.transactionMode,
      this.transactionStatus,
      this.date,
      this.time,
      this.currency,
      this.amount,
      this.payeeAvatarUrl,
      this.payerAvatarUrl});
}

List<TransactionModel> transactionData = [
  TransactionModel(
    payeeName: 'Utkarsh Mishra',
    payeeID: 'utkarshmishra@upi',
    payeeMobileNumber: '+919977642640',
    payerName: 'Shivam Goyal',
    payerID: 'shivamgoyal@upi',
    payerMobileNumber: '+919012218994',
    transactionID: '928523139261',
    transactionMode: 'NFC Mode',
    transactionStatus: 'pending',
    date: '12 Oct 2019',
    time: '11:16 PM',
    currency: 'INR',
    amount: '125.23',
    payeeAvatarUrl: 'assets/images/utkarsh.jpg',
    payerAvatarUrl: 'assets/images/shivam.jpg',
  ),
  TransactionModel(
    payeeName: 'Shivam Goyal',
    payeeID: 'shivamgoyal@upi',
    payeeMobileNumber: '+919012218994',
    payerName: 'Ambika Arora',
    payerID: 'ambikaarora@upi',
    payerMobileNumber: '+918564712367',
    transactionID: '928552369621',
    transactionMode: 'QR Mode',
    transactionStatus: 'success',
    date: '10 Oct 2019',
    time: '12:26 AM',
    currency: 'INR',
    amount: '236.20',
    payeeAvatarUrl: 'assets/images/shivam.jpg',
    payerAvatarUrl: 'assets/images/ambika.jpg',
  ),
  TransactionModel(
    payeeName: 'Utkarsh Mishra',
    payeeID: 'utkarshmishra@upi',
    payeeMobileNumber: '+919977642640',
    payerName: 'Shivam Goyal',
    payerID: 'shivamgoyal@upi',
    payerMobileNumber: '+919012218994',
    transactionID: '928523139261',
    transactionMode: 'NFC Mode',
    transactionStatus: 'success',
    date: '08 Oct 2019',
    time: '11:16 PM',
    currency: 'INR',
    amount: '895.23',
    payeeAvatarUrl: 'assets/images/utkarsh.jpg',
    payerAvatarUrl: 'assets/images/shivam.jpg',
  ),
  TransactionModel(
    payeeName: 'Shivam Goyal',
    payeeID: 'shivamgoyal@upi',
    payeeMobileNumber: '+919012218994',
    payerName: 'Mankaran Singh',
    payerID: 'mankaransingh@upi',
    payerMobileNumber: '+914567981235',
    transactionID: '928523139621',
    transactionMode: 'QR Mode',
    transactionStatus: 'failed',
    date: '07 Oct 2019',
    time: '12:26 AM',
    currency: 'INR',
    amount: '95.20',
    payeeAvatarUrl: 'assets/images/shivam.jpg',
    payerAvatarUrl: 'assets/images/mankaran.jpg',
  ),
  TransactionModel(
    payeeName: 'Utkarsh Mishra',
    payeeID: 'utkarshmishra@upi',
    payeeMobileNumber: '+919977642640',
    payerName: 'Shivam Goyal',
    payerID: 'shivamgoyal@upi',
    payerMobileNumber: '+919012218994',
    transactionID: '928523139261',
    transactionMode: 'NFC Mode',
    transactionStatus: 'success',
    date: '01 Oct 2019',
    time: '11:16 PM',
    currency: 'INR',
    amount: '143.23',
    payeeAvatarUrl: 'assets/images/utkarsh.jpg',
    payerAvatarUrl: 'assets/images/shivam.jpg',
  ),
  TransactionModel(
    payeeName: 'Shivam Goyal',
    payeeID: 'shivamgoyal@upi',
    payeeMobileNumber: '+919012218994',
    payerName: 'Mankaran Singh',
    payerID: 'mankaransingh@upi',
    payerMobileNumber: '+914567981235',
    transactionID: '928523139621',
    transactionMode: 'QR Mode',
    transactionStatus: 'success',
    date: '30 Sep 2019',
    time: '12:26 AM',
    currency: 'INR',
    amount: '200.00',
    payeeAvatarUrl: 'assets/images/shivam.jpg',
    payerAvatarUrl: 'assets/images/mankaran.jpg',
  ),
  TransactionModel(
    payeeName: 'Khushboo Verma',
    payeeID: 'khushbooverma@upi',
    payeeMobileNumber: '+916941236952',
    payerName: 'Shivam Goyal',
    payerID: 'shivamgoyal@upi',
    payerMobileNumber: '+919012218994',
    transactionID: '928523139261',
    transactionMode: 'NFC Mode',
    transactionStatus: 'failed',
    date: '15 Sep 2019',
    time: '11:16 PM',
    currency: 'INR',
    amount: '652.56',
    payeeAvatarUrl: 'assets/images/khushboo.jpg',
    payerAvatarUrl: 'assets/images/shivam.jpg',
  ),
  TransactionModel(
    payeeName: 'Shivam Goyal',
    payeeID: 'shivamgoyal@upi',
    payeeMobileNumber: '+919012218994',
    payerName: 'Mankaran Singh',
    payerID: 'mankaransingh@upi',
    payerMobileNumber: '+914567981235',
    transactionID: '928523139621',
    transactionMode: 'QR Mode',
    transactionStatus: 'success',
    date: '11 Sep 2019',
    time: '12:26 AM',
    currency: 'INR',
    amount: '62.20',
    payeeAvatarUrl: 'assets/images/shivam.jpg',
    payerAvatarUrl: 'assets/images/mankaran.jpg',
  ),
  TransactionModel(
    payeeName: 'Utkarsh Mishra',
    payeeID: 'utkarshmishra@upi',
    payeeMobileNumber: '+919977642640',
    payerName: 'Shivam Goyal',
    payerID: 'shivamgoyal@upi',
    payerMobileNumber: '+919012218994',
    transactionID: '928523139261',
    transactionMode: 'NFC Mode',
    transactionStatus: 'failed',
    date: '09 Sep 2019',
    time: '11:16 PM',
    currency: 'INR',
    amount: '456.23',
    payeeAvatarUrl: 'assets/images/utkarsh.jpg',
    payerAvatarUrl: 'assets/images/shivam.jpg',
  ),
  TransactionModel(
    payeeName: 'Shivam Goyal',
    payeeID: 'shivamgoyal@upi',
    payeeMobileNumber: '+919012218994',
    payerName: 'Mankaran Singh',
    payerID: 'mankaransingh@upi',
    payerMobileNumber: '+914567981235',
    transactionID: '928523139621',
    transactionMode: 'QR Mode',
    transactionStatus: 'success',
    date: '09 Sep 2019',
    time: '08:56 AM',
    currency: 'INR',
    amount: '165.00',
    payeeAvatarUrl: 'assets/images/shivam.jpg',
    payerAvatarUrl: 'assets/images/mankaran.jpg',
  ),
];
